apiVersion: v1
kind: Pod
metadata:
  name: "pod1"
  namespace: default
  labels:
    app: "pod1"
spec:
  containers:
  - name: pod1
    image: "ichte/swarmtest:node"
    resources:
      limits:
        cpu: 100m
        memory: 150M
    ports:
    - containerPort:  8085
  restartPolicy: Always