apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiktok-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiktok-app
  template:
    metadata:
      labels:
        app: tiktok-app
    spec:
      containers:
      - name: tiktok-be
        image: gcr.io/tiktok-395207/tiktok_be@sha256:c01835ed77cee170307cd7ef02e0a524740556fdc35243a90e6b7c65dd67ede5
        ports:
        - containerPort: 8888
        envFrom:
        - configMapRef:
            name: tiktok-app-config
      - name: mongo-db
        image: gcr.io/tiktok-395207/mongo@sha256:e4d7cef25cd0d70c3f6f72566f5b46bda6b1978716cee6a3b341d8bd3d9fe69a
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: tiktok-app
spec:
  type: LoadBalancer
  selector:
    app: tiktok-app
  ports:
  - name: backend
    protocol: TCP
    port: 8888
    targetPort: 8888
  - name: mongo-db
    protocol: TCP
    port: 27017
    targetPort: 27017
  