apiVersion: v1
kind: Endpoints
metadata:
  name: outside-enpoint
subsets:
  - addresses:
      - ip: 192.168.0.125
    ports:
      - port: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: outside-enpoint
spec:
  ports:
    - port: 31883
      targetPort: 1883