apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
      - name: guacamole
        image: tungvt.vn/guacamole-dev
        ports:
        - containerPort: 9632
      imagePullSecrets:
      - name: mycredential
      - name: myca

---
apiVersion: v1
kind: Service
metadata:
  name: guacamole-svc
spec:
  type: NodePort
  ports:
  - port: 4821 
    targetPort: 9632
    protocol: TCP
    name: http
    nodePort: 31021
  selector:
    app: guacamole