apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guacd
  template:
    metadata:
      labels:
        app: guacd
    spec:
      containers:
      - name: guacd
        image: guacamole/guacd
        ports:
        - containerPort: 4822

---
apiVersion: v1
kind: Service
metadata:
  name: gua-svc
spec:
  type: ClusterIP
  ports:
  - port: 4822
    targetPort: 4822
    protocol: TCP
    name: guacd
  selector:
    app: guacd
