registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  volumes:
    - /mnt/registry:/var/lib/registry
    - /path/data:/var/lib/registry
    - /path/certs:/certs
    - /path/auth:/auth
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
